/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Memory {
  'id' : bigint,
  'storyText' : string,
  'specialMemory' : boolean,
  'voiceNoteUrl' : string,
  'year' : bigint,
  'photoUrl' : string,
  'sceneType' : string,
  'isSecret' : boolean,
  'location' : string,
  'subtitle' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new memory. Admin only.
   */
  'createMemory' : ActorMethod<[Memory], undefined>,
  /**
   * / Delete a memory. Admin only.
   */
  'deleteMemory' : ActorMethod<[bigint], undefined>,
  /**
   * / Get all memories.
   * / Authenticated users (role: user or admin) see all memories including secret ones.
   * / Guests only see non-secret memories.
   */
  'getAllMemories' : ActorMethod<[], Array<Memory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a memory by ID.
   * / Secret memories are only visible to authenticated users (role: user or admin).
   * / Guests may only view non-secret memories.
   */
  'getMemoryById' : ActorMethod<[bigint], [] | [Memory]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get the count of viewed memories. Requires authenticated user.
   */
  'getViewedMemoriesCount' : ActorMethod<[], bigint>,
  /**
   * / Get all viewed memory IDs. Requires authenticated user.
   */
  'getViewedMemoryIds' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Mark a memory as viewed. Requires authenticated user (member or admin).
   * / Guests cannot track viewed memories since the unlock logic is per-user session.
   */
  'markMemoryViewed' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update an existing memory. Admin only.
   */
  'updateMemory' : ActorMethod<[bigint, Memory], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];