/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Memory = IDL.Record({
  'id' : IDL.Nat,
  'storyText' : IDL.Text,
  'specialMemory' : IDL.Bool,
  'voiceNoteUrl' : IDL.Text,
  'year' : IDL.Nat,
  'photoUrl' : IDL.Text,
  'sceneType' : IDL.Text,
  'isSecret' : IDL.Bool,
  'location' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMemory' : IDL.Func([Memory], [], []),
  'deleteMemory' : IDL.Func([IDL.Nat], [], []),
  'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMemoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Memory)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getViewedMemoriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getViewedMemoryIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMemoryViewed' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMemory' : IDL.Func([IDL.Nat, Memory], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Memory = IDL.Record({
    'id' : IDL.Nat,
    'storyText' : IDL.Text,
    'specialMemory' : IDL.Bool,
    'voiceNoteUrl' : IDL.Text,
    'year' : IDL.Nat,
    'photoUrl' : IDL.Text,
    'sceneType' : IDL.Text,
    'isSecret' : IDL.Bool,
    'location' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMemory' : IDL.Func([Memory], [], []),
    'deleteMemory' : IDL.Func([IDL.Nat], [], []),
    'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMemoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Memory)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getViewedMemoriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getViewedMemoryIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMemoryViewed' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMemory' : IDL.Func([IDL.Nat, Memory], [], []),
  });
};

export const init = ({ IDL }) => { return []; };